name: Docker Build & Deploy to Render

on:
  push:
    branches: [ "main" ]  # Hangi branch'e pushlanınca çalışsın? (Genelde main veya master)
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: backendEnv

    steps:
      # 1. Kodları Github'dan sanal makineye çeker
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Docker Hub'a giriş yapar
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker Image'ını build eder ve Docker Hub'a gönderir (Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile'ın bulunduğu dizin (Kök dizindeyse nokta kalsın)
          push: true
          # Image etiketi: kadi/image-adi:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/demirkayarendevbe-backend:latest 
          

      # 4. Render'daki Deploy Hook URL'ini tetikler
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
